name: frosty
repository: https://github.com/peercoin/frosty

packages:
  - frosty/

scripts:

  analyze:
    exec: dart analyze .

  build:linux:
    run: bash scripts/build-linux.sh
    description: Build the Rust library for Linux using Podman/Docker

  build:android:
    run: bash scripts/build-android.sh
    description: Build the Rust library for Android using Podman/Docker

  build:dev:
    run: bash scripts/build-dev.sh
    description: Build the debug Rust library for Linux and generate bindings

  test:
    run: melos exec -c 1 --fail-fast -- "dart test"
    description: Run Dart tests
    packageFilters:
      flutter: false
      dir-exists: test
