name: frosty_example
description: "Demonstrates how to use frosty from Flutter"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  coinlib: '>=5.0.0 <7.0.0'
  frosty:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
