name: frosty
description: FROST threshold Schnorr signatures using an underlying Rust library
version: 2.0.0
repository: https://github.com/peercoin/frosty

environment:
  sdk: ^3.2.0

dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^2.9.0
  path: ^1.8.3
  coinlib: ^4.0.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  ffigen: ^16.0.0
  freezed: ^2.4.7
  lints: ^5.1.1
  test: ^1.24.0
