name: frosty
description: FROST threshold Schnorr signatures using an underlying Rust library
version: 1.0.0
repository: https://github.com/peercoin/frosty

environment:
  sdk: ^3.2.0

dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: 2.0.0-dev.28
  path: ^1.8.3
  coinlib: ^2.1.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  # FRB requires v9 or it fails
  build_runner: ^2.4.8
  ffigen: ^9.0.0
  freezed: ^2.4.7
  lints: ^3.0.0
  test: ^1.24.0
