[package]
name = "frosty_rust"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.*"

[dependencies]
anyhow = "1.0.75"
flutter_rust_bridge = "1.82.*"
frost-secp256k1 = "0.7.0"
